spring:
  application:
      name: backend
  data:
      mongodb:
        uri: mongodb://localhost:27017/CafeManager
server: 
  port: 8080
jwt:
  secret: thisIsVerySecretChangeItPls
  expiration-ms: 86400000
